### ISSUE TITLE
Ability for other DHBWs to use the app

### ISSUE THREAD

**Issue by d-Rickyy-b** [dhbw-timetable/dhbw-timetable-android#85]
Currently there is no way to use your app, when you are coming from e.g. the DHBW @ Karlsruhe.

Changing the "parsing logic" into a regular expression would allow students from other DHBWs to use your app aswell. Here's the baseURL for Karlsruhe `https://rapla.dhbw-karlsruhe.de/rapla?key=`.

Besides that, there are also special Rapla URLs like this one `https://rapla.dhbw-karlsruhe.de/rapla?page=calendar&user=vollmer&file=tinf15b3&today=Heute` which could be supported aswell.

https://github.com/dhbw-timetable/dhbw-timetable-android/blob/2c44e3b9fddcb72e9d7c719196c937546e1fb015/app/src/main/java/dhbw/timetable/navfragments/preferences/timetables/NewTimetableActivity.java#L43-L54

Greetings from the DHBW Karlsruhe

**Comment by hendriku** [comment]
Thank you for providing this information. It would be very cool if students from other DHBW schools would also be able to use our app! I like your suggestion of validating the baseURL via regular expressions and will take a look at it soon! :)

**Comment by hendriku** [comment]
Hey @d-Rickyy-b Check out this project https://github.com/dhbw-timetable/rapla-parser . It's the new version of our rapla parsing API and we will implement for the app in the near future. 

It supports also **karlsruhe** and **mannheim** base URLs and runs quite good on our test links. 

We still have a few issues like e.g. the API can't get the course title totally reliable. This is because karlsruhe uses a partially different markup structure than stuttgart. It will be fixed in one of the next version.

**Comment by d-Rickyy-b** [comment]
Nice, it looks great. Will have a deeper look into it in the future :)

If you want, you can contact me on [Telegram](https://telegram.org/dl) via my username [@d_Rickyy_b](https://t.me/d_Rickyy_b).

**Comment by hendriku** [comment]
@d-Rickyy-b Proud to announce: the app v1.2 will support the new links and even display parallel lectures. 🎉 I'll message you on telegram soon so we can have a talk about this.

**Comment by d-Rickyy-b** [comment]
Sounds great, I'll take a look.
